# ==========================================
# SERVER
# ==========================================
server.port=8080

# ==========================================
# DATABASE CONFIGURATION (Render PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://dpg-d9d1rvf41pts73de43k0-a.oregon-postgres.render.com:5432/train_reservation_db_xw8m?sslmode=require
spring.datasource.username=root
spring.datasource.password=1paxMPAEzOudqKawEDF2ygF7xf2SFT7E
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# LOGGING
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE