spring.application.name=train-reservation-portal

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/train_reservation_db
spring.datasource.username=root
spring.datasource.password=2307

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true